[package]
name = "nwg-hdpi-plotting"
version = "1.0.0"
edition = "2024"
build = "build.rs"

[dependencies]
native-windows-derive = { path = "../../../native-windows-derive" }
native-windows-gui = { path = "../../", features = ["high-dpi"] }
plotters = { version = "0.3", default-features = false, features = [
  "all_elements",
  "all_series"
] }

[build-dependencies]
embed-resource = "1.3"
