[package]
name = "native-windows-canvas"
version = "0.0.1"
edition = "2024"
description = "A low level Direct2D wrapper for native-windows-gui"
documentation = "https://gabdube.github.io/native-windows-gui/native-windows-docs/index.html"
repository = "https://github.com/gabdube/native-windows-gui"
license = "MIT"
keywords = ["direct2d", "graphics", "gui", "ui", "windows"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
