//! Windows virtual key code

use enum_discriminant::discriminant;

use crate::{EventData, win32::keys::get_key_state};

bitflags! {
    pub struct ModifierKeys: u8 {
        const NONE = 0;
        const SHIFT = 1;
        const ALT = 1 << 1;
        const CTRL = 1 << 2;

        const ALT_SHIFT =  ModifierKeys::ALT.bits | ModifierKeys::SHIFT.bits;
        const CTRL_SHIFT =  ModifierKeys::CTRL.bits | ModifierKeys::SHIFT.bits;
        const CTRL_ALT =  ModifierKeys::CTRL.bits | ModifierKeys::ALT.bits;
        const CTRL_ALT_SHIFT =  ModifierKeys::CTRL.bits | ModifierKeys::ALT.bits| ModifierKeys::SHIFT.bits;
    }
}

/// Denotes a key combo to be tied to a shortcut.
#[derive(Copy, Clone, Debug)]
pub struct KeyCombo {
    pub modifiers: ModifierKeys,
    pub key: KeyPress,
}

impl KeyCombo {
    pub fn read(event_data: &EventData) -> Option<Self> {
        Some(Self {
            key: KeyPress::from_discriminant(event_data.on_key())?,
            modifiers: ModifierKeys {
                bits: get_key_state(CONTROL) * ModifierKeys::CTRL.bits()
                    | get_key_state(ALT) * ModifierKeys::ALT.bits()
                    | get_key_state(SHIFT) * ModifierKeys::SHIFT.bits(),
            },
        })
    }
    pub const fn new(modifiers: ModifierKeys, key: KeyPress) -> Self {
        Self { modifiers, key }
    }
}

/// A subset of VirtualKey. Denotes the key press portion of a key combo.
#[derive(Copy, Clone, Debug)]
#[discriminant(u32)]
pub enum KeyPress {
    Back = BACK,
    Tab = TAB,
    Clear = CLEAR,
    Return = RETURN,
    Pause = PAUSE,
    Capital = CAPITAL,
    Hangul = HANGUL,
    Junja = JUNJA,
    Final = FINAL,
    Kanji = KANJI,
    Escape = ESCAPE,
    Convert = CONVERT,
    Nonconvert = NONCONVERT,
    Accept = ACCEPT,
    Modechange = MODECHANGE,
    Space = SPACE,
    Prior = PRIOR,
    Next = NEXT,
    End = END,
    Home = HOME,
    Left = LEFT,
    Up = UP,
    Right = RIGHT,
    Down = DOWN,
    Select = SELECT,
    Print = PRINT,
    Execute = EXECUTE,
    Snapshot = SNAPSHOT,
    Insert = INSERT,
    Delete = DELETE,
    Help = HELP,
    Key0 = _0,
    Key1 = _1,
    Key2 = _2,
    Key3 = _3,
    Key4 = _4,
    Key5 = _5,
    Key6 = _6,
    Key7 = _7,
    Key8 = _8,
    Key9 = _9,
    A = _A,
    B = _B,
    C = _C,
    D = _D,
    E = _E,
    F = _F,
    G = _G,
    H = _H,
    I = _I,
    J = _J,
    K = _K,
    L = _L,
    M = _M,
    N = _N,
    O = _O,
    P = _P,
    Q = _Q,
    R = _R,
    S = _S,
    T = _T,
    U = _U,
    V = _V,
    W = _W,
    X = _X,
    Y = _Y,
    Z = _Z,
    Lwin = LWIN,
    Rwin = RWIN,
    Apps = APPS,
    Sleep = SLEEP,

    Numpad0 = NUMPAD0,
    Numpad1 = NUMPAD1,
    Numpad2 = NUMPAD2,
    Numpad3 = NUMPAD3,
    Numpad4 = NUMPAD4,
    Numpad5 = NUMPAD5,
    Numpad6 = NUMPAD6,
    Numpad7 = NUMPAD7,
    Numpad8 = NUMPAD8,
    Numpad9 = NUMPAD9,
    NumpadTimes = MULTIPLY,
    NumpadPlus = ADD,
    Separator = SEPARATOR,
    NumpadMinus = SUBTRACT,
    Decimal = DECIMAL,
    NumpadSlash = DIVIDE,

    F1 = F1,
    F2 = F2,
    F3 = F3,
    F4 = F4,
    F5 = F5,
    F6 = F6,
    F7 = F7,
    F8 = F8,
    F9 = F9,
    F10 = F10,
    F11 = F11,
    F12 = F12,
    F13 = F13,
    F14 = F14,
    F15 = F15,
    F16 = F16,
    F17 = F17,
    F18 = F18,
    F19 = F19,
    F20 = F20,
    F21 = F21,
    F22 = F22,
    F23 = F23,
    F24 = F24,

    Numlock = NUMLOCK,
    Scroll = SCROLL,

    Lshift = LSHIFT,
    Rshift = RSHIFT,
    Lcontrol = LCONTROL,
    Rcontrol = RCONTROL,
    Lmenu = LMENU,
    Rmenu = RMENU,
    BrowserBack = BROWSER_BACK,
    BrowserForward = BROWSER_FORWARD,
    BrowserRefresh = BROWSER_REFRESH,
    BrowserStop = BROWSER_STOP,
    BrowserSearch = BROWSER_SEARCH,
    BrowserFavorites = BROWSER_FAVORITES,
    BrowserHome = BROWSER_HOME,
    VolumeMute = VOLUME_MUTE,
    VolumeDown = VOLUME_DOWN,
    VolumeUp = VOLUME_UP,
    MediaNextTrack = MEDIA_NEXT_TRACK,
    MediaPrevTrack = MEDIA_PREV_TRACK,
    MediaStop = MEDIA_STOP,
    MediaPlayPause = MEDIA_PLAY_PAUSE,
    LaunchMail = LAUNCH_MAIL,
    LaunchMediaSelect = LAUNCH_MEDIA_SELECT,
    LaunchApp1 = LAUNCH_APP1,
    LaunchApp2 = LAUNCH_APP2,
    Colon = OEM_1,
    Plus = OEM_PLUS,
    Comma = OEM_COMMA,
    Minus = OEM_MINUS,
    Period = OEM_PERIOD,
    Slash = OEM_2,
    Tilde = OEM_3,
    LBracket = OEM_4,
    Backslash = OEM_5,
    RBracket = OEM_6,
    Oem7 = OEM_7,
    Oem8 = OEM_8,
    Oem9 = OEM_9,
    Oem102 = OEM_102,
    Oem10 = OEM_10,
    Oem11 = OEM_11,
    Processkey = PROCESSKEY,
    OemX = OEM_X,
    Packet = PACKET,
    Oem12 = OEM_12,
    Oem13 = OEM_13,
    Oem14 = OEM_14,
    Oem15 = OEM_15,
    Oem16 = OEM_16,
    Oem17 = OEM_17,
    Oem18 = OEM_18,
    Oem19 = OEM_19,
    Oem20 = OEM_20,
    Oem21 = OEM_21,
    Oem22 = OEM_22,
    Oem23 = OEM_23,
    Oem24 = OEM_24,
    Oem25 = OEM_25,
    Oem26 = OEM_26,
    Oem27 = OEM_27,
    Oem28 = OEM_28,
    Oem29 = OEM_29,
    Attn = ATTN,
    Crsel = CRSEL,
    Exsel = EXSEL,
    Ereof = EREOF,
    Play = PLAY,
    Zoom = ZOOM,
    Pa1 = PA1,
    OemClear = OEM_CLEAR,
}

/// Most of the w32 virtual key codes.
#[derive(Copy, Clone, Debug)]
#[discriminant(u32)]
pub enum VirtualKey {
    Back = BACK,
    Tab = TAB,
    Clear = CLEAR,
    Return = RETURN,
    Shift = SHIFT,
    Control = CONTROL,
    Alt = ALT,
    Pause = PAUSE,
    Capital = CAPITAL,
    Hangul = HANGUL,
    Junja = JUNJA,
    Final = FINAL,
    Kanji = KANJI,
    Escape = ESCAPE,
    Convert = CONVERT,
    Nonconvert = NONCONVERT,
    Accept = ACCEPT,
    Modechange = MODECHANGE,
    Space = SPACE,
    Prior = PRIOR,
    Next = NEXT,
    End = END,
    Home = HOME,
    Left = LEFT,
    Up = UP,
    Right = RIGHT,
    Down = DOWN,
    Select = SELECT,
    Print = PRINT,
    Execute = EXECUTE,
    Snapshot = SNAPSHOT,
    Insert = INSERT,
    Delete = DELETE,
    Help = HELP,
    Key0 = _0,
    Key1 = _1,
    Key2 = _2,
    Key3 = _3,
    Key4 = _4,
    Key5 = _5,
    Key6 = _6,
    Key7 = _7,
    Key8 = _8,
    Key9 = _9,
    A = _A,
    B = _B,
    C = _C,
    D = _D,
    E = _E,
    F = _F,
    G = _G,
    H = _H,
    I = _I,
    J = _J,
    K = _K,
    L = _L,
    M = _M,
    N = _N,
    O = _O,
    P = _P,
    Q = _Q,
    R = _R,
    S = _S,
    T = _T,
    U = _U,
    V = _V,
    W = _W,
    X = _X,
    Y = _Y,
    Z = _Z,
    Lwin = LWIN,
    Rwin = RWIN,
    Apps = APPS,
    Sleep = SLEEP,

    Numpad0 = NUMPAD0,
    Numpad1 = NUMPAD1,
    Numpad2 = NUMPAD2,
    Numpad3 = NUMPAD3,
    Numpad4 = NUMPAD4,
    Numpad5 = NUMPAD5,
    Numpad6 = NUMPAD6,
    Numpad7 = NUMPAD7,
    Numpad8 = NUMPAD8,
    Numpad9 = NUMPAD9,
    NumpadTimes = MULTIPLY,
    NumpadPlus = ADD,
    Separator = SEPARATOR,
    NumpadMinus = SUBTRACT,
    Decimal = DECIMAL,
    NumpadSlash = DIVIDE,

    F1 = F1,
    F2 = F2,
    F3 = F3,
    F4 = F4,
    F5 = F5,
    F6 = F6,
    F7 = F7,
    F8 = F8,
    F9 = F9,
    F10 = F10,
    F11 = F11,
    F12 = F12,
    F13 = F13,
    F14 = F14,
    F15 = F15,
    F16 = F16,
    F17 = F17,
    F18 = F18,
    F19 = F19,
    F20 = F20,
    F21 = F21,
    F22 = F22,
    F23 = F23,
    F24 = F24,

    Numlock = NUMLOCK,
    Scroll = SCROLL,

    Lshift = LSHIFT,
    Rshift = RSHIFT,
    Lcontrol = LCONTROL,
    Rcontrol = RCONTROL,
    Lmenu = LMENU,
    Rmenu = RMENU,
    BrowserBack = BROWSER_BACK,
    BrowserForward = BROWSER_FORWARD,
    BrowserRefresh = BROWSER_REFRESH,
    BrowserStop = BROWSER_STOP,
    BrowserSearch = BROWSER_SEARCH,
    BrowserFavorites = BROWSER_FAVORITES,
    BrowserHome = BROWSER_HOME,
    VolumeMute = VOLUME_MUTE,
    VolumeDown = VOLUME_DOWN,
    VolumeUp = VOLUME_UP,
    MediaNextTrack = MEDIA_NEXT_TRACK,
    MediaPrevTrack = MEDIA_PREV_TRACK,
    MediaStop = MEDIA_STOP,
    MediaPlayPause = MEDIA_PLAY_PAUSE,
    LaunchMail = LAUNCH_MAIL,
    LaunchMediaSelect = LAUNCH_MEDIA_SELECT,
    LaunchApp1 = LAUNCH_APP1,
    LaunchApp2 = LAUNCH_APP2,
    Colon = OEM_1,
    Plus = OEM_PLUS,
    Comma = OEM_COMMA,
    Minus = OEM_MINUS,
    Period = OEM_PERIOD,
    Slash = OEM_2,
    Tilde = OEM_3,
    LBracket = OEM_4,
    Backslash = OEM_5,
    RBracket = OEM_6,
    Oem7 = OEM_7,
    Oem8 = OEM_8,
    Oem9 = OEM_9,
    Oem102 = OEM_102,
    Oem10 = OEM_10,
    Oem11 = OEM_11,
    Processkey = PROCESSKEY,
    OemX = OEM_X,
    Packet = PACKET,
    Oem12 = OEM_12,
    Oem13 = OEM_13,
    Oem14 = OEM_14,
    Oem15 = OEM_15,
    Oem16 = OEM_16,
    Oem17 = OEM_17,
    Oem18 = OEM_18,
    Oem19 = OEM_19,
    Oem20 = OEM_20,
    Oem21 = OEM_21,
    Oem22 = OEM_22,
    Oem23 = OEM_23,
    Oem24 = OEM_24,
    Oem25 = OEM_25,
    Oem26 = OEM_26,
    Oem27 = OEM_27,
    Oem28 = OEM_28,
    Oem29 = OEM_29,
    Attn = ATTN,
    Crsel = CRSEL,
    Exsel = EXSEL,
    Ereof = EREOF,
    Play = PLAY,
    Zoom = ZOOM,
    Noname = NONAME,
    Pa1 = PA1,
    OemClear = OEM_CLEAR,

    GamepadA = GAMEPAD_A,
    GamepadB = GAMEPAD_B,
    GamepadX = GAMEPAD_X,
    GamepadY = GAMEPAD_Y,
    GamepadR1 = GAMEPAD_RIGHT_SHOULDER,
    GamepadL1 = GAMEPAD_LEFT_SHOULDER,
    GamepadL2 = GAMEPAD_LEFT_TRIGGER,
    GamepadR2 = GAMEPAD_RIGHT_TRIGGER,
    GamepadDpadUp = GAMEPAD_DPAD_UP,
    GamepadDpadDown = GAMEPAD_DPAD_DOWN,
    GamepadDpadLeft = GAMEPAD_DPAD_LEFT,
    GamepadDpadRight = GAMEPAD_DPAD_RIGHT,
    GamepadStart = GAMEPAD_MENU,
    GamepadSelect = GAMEPAD_VIEW,
    GamepadL3 = GAMEPAD_LEFT_THUMBSTICK_BUTTON,
    GamepadR3 = GAMEPAD_RIGHT_THUMBSTICK_BUTTON,
    GamepadLeftStickUp = GAMEPAD_LEFT_THUMBSTICK_UP,
    GamepadLeftStickDown = GAMEPAD_LEFT_THUMBSTICK_DOWN,
    GamepadLeftStickRight = GAMEPAD_LEFT_THUMBSTICK_RIGHT,
    GamepadLeftStickLeft = GAMEPAD_LEFT_THUMBSTICK_LEFT,
    GamepadRightStickUp = GAMEPAD_RIGHT_THUMBSTICK_UP,
    GamepadRightStickDown = GAMEPAD_RIGHT_THUMBSTICK_DOWN,
    GamepadRightStickRight = GAMEPAD_RIGHT_THUMBSTICK_RIGHT,
    GamepadRightStickLeft = GAMEPAD_RIGHT_THUMBSTICK_LEFT,
}

pub const BACK: u32 = 0x08;
pub const TAB: u32 = 0x09;
pub const CLEAR: u32 = 0x0C;
pub const RETURN: u32 = 0x0D;
pub const SHIFT: u32 = 0x10;
pub const CONTROL: u32 = 0x11;
pub const ALT: u32 = 0x12;
pub const PAUSE: u32 = 0x13;
pub const CAPITAL: u32 = 0x14;
pub const KANA: u32 = 0x15;
pub const HANGUEL: u32 = 0x15;
pub const HANGUL: u32 = 0x15;
pub const JUNJA: u32 = 0x17;
pub const FINAL: u32 = 0x18;
pub const HANJA: u32 = 0x19;
pub const KANJI: u32 = 0x19;
pub const ESCAPE: u32 = 0x1B;
pub const CONVERT: u32 = 0x1C;
pub const NONCONVERT: u32 = 0x1D;
pub const ACCEPT: u32 = 0x1E;
pub const MODECHANGE: u32 = 0x1F;
pub const SPACE: u32 = 0x20;
pub const PRIOR: u32 = 0x21;
pub const NEXT: u32 = 0x22;
pub const END: u32 = 0x23;
pub const HOME: u32 = 0x24;
pub const LEFT: u32 = 0x25;
pub const UP: u32 = 0x26;
pub const RIGHT: u32 = 0x27;
pub const DOWN: u32 = 0x28;
pub const SELECT: u32 = 0x29;
pub const PRINT: u32 = 0x2A;
pub const EXECUTE: u32 = 0x2B;
pub const SNAPSHOT: u32 = 0x2C;
pub const INSERT: u32 = 0x2D;
pub const DELETE: u32 = 0x2E;
pub const HELP: u32 = 0x2F;
pub const _0: u32 = 0x30;
pub const _1: u32 = 0x31;
pub const _2: u32 = 0x32;
pub const _3: u32 = 0x33;
pub const _4: u32 = 0x34;
pub const _5: u32 = 0x35;
pub const _6: u32 = 0x36;
pub const _7: u32 = 0x37;
pub const _8: u32 = 0x38;
pub const _9: u32 = 0x39;
pub const _A: u32 = 0x41;
pub const _B: u32 = 0x42;
pub const _C: u32 = 0x43;
pub const _D: u32 = 0x44;
pub const _E: u32 = 0x45;
pub const _F: u32 = 0x46;
pub const _G: u32 = 0x47;
pub const _H: u32 = 0x48;
pub const _I: u32 = 0x49;
pub const _J: u32 = 0x4A;
pub const _K: u32 = 0x4B;
pub const _L: u32 = 0x4C;
pub const _M: u32 = 0x4D;
pub const _N: u32 = 0x4E;
pub const _O: u32 = 0x4F;
pub const _P: u32 = 0x50;
pub const _Q: u32 = 0x51;
pub const _R: u32 = 0x52;
pub const _S: u32 = 0x53;
pub const _T: u32 = 0x54;
pub const _U: u32 = 0x55;
pub const _V: u32 = 0x56;
pub const _W: u32 = 0x57;
pub const _X: u32 = 0x58;
pub const _Y: u32 = 0x59;
pub const _Z: u32 = 0x5A;
pub const LWIN: u32 = 0x5B;
pub const RWIN: u32 = 0x5C;
pub const APPS: u32 = 0x5D;
pub const SLEEP: u32 = 0x5F;
pub const NUMPAD0: u32 = 0x60;
pub const NUMPAD1: u32 = 0x61;
pub const NUMPAD2: u32 = 0x62;
pub const NUMPAD3: u32 = 0x63;
pub const NUMPAD4: u32 = 0x64;
pub const NUMPAD5: u32 = 0x65;
pub const NUMPAD6: u32 = 0x66;
pub const NUMPAD7: u32 = 0x67;
pub const NUMPAD8: u32 = 0x68;
pub const NUMPAD9: u32 = 0x69;
pub const MULTIPLY: u32 = 0x6A;
pub const ADD: u32 = 0x6B;
pub const SEPARATOR: u32 = 0x6C;
pub const SUBTRACT: u32 = 0x6D;
pub const DECIMAL: u32 = 0x6E;
pub const DIVIDE: u32 = 0x6F;
pub const F1: u32 = 0x70;
pub const F2: u32 = 0x71;
pub const F3: u32 = 0x72;
pub const F4: u32 = 0x73;
pub const F5: u32 = 0x74;
pub const F6: u32 = 0x75;
pub const F7: u32 = 0x76;
pub const F8: u32 = 0x77;
pub const F9: u32 = 0x78;
pub const F10: u32 = 0x79;
pub const F11: u32 = 0x7A;
pub const F12: u32 = 0x7B;
pub const F13: u32 = 0x7C;
pub const F14: u32 = 0x7D;
pub const F15: u32 = 0x7E;
pub const F16: u32 = 0x7F;
pub const F17: u32 = 0x80;
pub const F18: u32 = 0x81;
pub const F19: u32 = 0x82;
pub const F20: u32 = 0x83;
pub const F21: u32 = 0x84;
pub const F22: u32 = 0x85;
pub const F23: u32 = 0x86;
pub const F24: u32 = 0x87;
pub const NUMLOCK: u32 = 0x90;
pub const SCROLL: u32 = 0x91;
pub const OEM_25: u32 = 0x92;
pub const OEM_26: u32 = 0x93;
pub const OEM_27: u32 = 0x94;
pub const OEM_28: u32 = 0x95;
pub const OEM_29: u32 = 0x96;
pub const LSHIFT: u32 = 0xA0;
pub const RSHIFT: u32 = 0xA1;
pub const LCONTROL: u32 = 0xA2;
pub const RCONTROL: u32 = 0xA3;
pub const LMENU: u32 = 0xA4;
pub const RMENU: u32 = 0xA5;
pub const BROWSER_BACK: u32 = 0xA6;
pub const BROWSER_FORWARD: u32 = 0xA7;
pub const BROWSER_REFRESH: u32 = 0xA8;
pub const BROWSER_STOP: u32 = 0xA9;
pub const BROWSER_SEARCH: u32 = 0xAA;
pub const BROWSER_FAVORITES: u32 = 0xAB;
pub const BROWSER_HOME: u32 = 0xAC;
pub const VOLUME_MUTE: u32 = 0xAD;
pub const VOLUME_DOWN: u32 = 0xAE;
pub const VOLUME_UP: u32 = 0xAF;
pub const MEDIA_NEXT_TRACK: u32 = 0xB0;
pub const MEDIA_PREV_TRACK: u32 = 0xB1;
pub const MEDIA_STOP: u32 = 0xB2;
pub const MEDIA_PLAY_PAUSE: u32 = 0xB3;
pub const LAUNCH_MAIL: u32 = 0xB4;
pub const LAUNCH_MEDIA_SELECT: u32 = 0xB5;
pub const LAUNCH_APP1: u32 = 0xB6;
pub const LAUNCH_APP2: u32 = 0xB7;
pub const OEM_1: u32 = 0xBA;
pub const OEM_PLUS: u32 = 0xBB;
pub const OEM_COMMA: u32 = 0xBC;
pub const OEM_MINUS: u32 = 0xBD;
pub const OEM_PERIOD: u32 = 0xBE;
pub const OEM_2: u32 = 0xBF;
pub const OEM_3: u32 = 0xC0;
pub const GAMEPAD_A: u32 = 0xC3;
pub const GAMEPAD_B: u32 = 0xC4;
pub const GAMEPAD_X: u32 = 0xC5;
pub const GAMEPAD_Y: u32 = 0xC6;
pub const GAMEPAD_RIGHT_SHOULDER: u32 = 0xC7;
pub const GAMEPAD_LEFT_SHOULDER: u32 = 0xC8;
pub const GAMEPAD_LEFT_TRIGGER: u32 = 0xC9;
pub const GAMEPAD_RIGHT_TRIGGER: u32 = 0xCA;
pub const GAMEPAD_DPAD_UP: u32 = 0xCB;
pub const GAMEPAD_DPAD_DOWN: u32 = 0xCC;
pub const GAMEPAD_DPAD_LEFT: u32 = 0xCD;
pub const GAMEPAD_DPAD_RIGHT: u32 = 0xCE;
pub const GAMEPAD_MENU: u32 = 0xCF;
pub const GAMEPAD_VIEW: u32 = 0xD0;
pub const GAMEPAD_LEFT_THUMBSTICK_BUTTON: u32 = 0xD1;
pub const GAMEPAD_RIGHT_THUMBSTICK_BUTTON: u32 = 0xD2;
pub const GAMEPAD_LEFT_THUMBSTICK_UP: u32 = 0xD3;
pub const GAMEPAD_LEFT_THUMBSTICK_DOWN: u32 = 0xD4;
pub const GAMEPAD_LEFT_THUMBSTICK_RIGHT: u32 = 0xD5;
pub const GAMEPAD_LEFT_THUMBSTICK_LEFT: u32 = 0xD6;
pub const GAMEPAD_RIGHT_THUMBSTICK_UP: u32 = 0xD7;
pub const GAMEPAD_RIGHT_THUMBSTICK_DOWN: u32 = 0xD8;
pub const GAMEPAD_RIGHT_THUMBSTICK_RIGHT: u32 = 0xD9;
pub const GAMEPAD_RIGHT_THUMBSTICK_LEFT: u32 = 0xDA;
pub const OEM_4: u32 = 0xDB;
pub const OEM_5: u32 = 0xDC;
pub const OEM_6: u32 = 0xDD;
pub const OEM_7: u32 = 0xDE;
pub const OEM_8: u32 = 0xDF;
pub const OEM_9: u32 = 0xE1;
pub const OEM_102: u32 = 0xE2;
pub const OEM_10: u32 = 0xE3;
pub const OEM_11: u32 = 0xE4;
pub const PROCESSKEY: u32 = 0xE5;
pub const OEM_X: u32 = 0xE6;
pub const PACKET: u32 = 0xE7;
pub const OEM_12: u32 = 0xE9;
pub const OEM_13: u32 = 0xEA;
pub const OEM_14: u32 = 0xEB;
pub const OEM_15: u32 = 0xEC;
pub const OEM_16: u32 = 0xED;
pub const OEM_17: u32 = 0xEE;
pub const OEM_18: u32 = 0xEF;
pub const OEM_19: u32 = 0xF0;
pub const OEM_20: u32 = 0xF1;
pub const OEM_21: u32 = 0xF2;
pub const OEM_22: u32 = 0xF3;
pub const OEM_23: u32 = 0xF4;
pub const OEM_24: u32 = 0xF5;
pub const ATTN: u32 = 0xF6;
pub const CRSEL: u32 = 0xF7;
pub const EXSEL: u32 = 0xF8;
pub const EREOF: u32 = 0xF9;
pub const PLAY: u32 = 0xFA;
pub const ZOOM: u32 = 0xFB;
pub const NONAME: u32 = 0xFC;
pub const PA1: u32 = 0xFD;
pub const OEM_CLEAR: u32 = 0xFE;
