[package]
name = "syncdraw"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.6"
glutin = "0.21"
native-windows-derive = { path = "../../../native-windows-derive" }
native-windows-gui = { path = "../..", features = [
  "animation-timer",
  "cursor",
  "extern-canvas",
  "notice",
  "status-bar"
] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
  "memoryapi",
  "processthreadsapi",
  "psapi",
  "synchapi",
  "winuser"
] }
