[package]
name = "nwg-embed-resources"
version = "1.0.0"
edition = "2024"
build = "build.rs"

[dependencies]
native-windows-derive = { path = "../../../native-windows-derive" }
native-windows-gui = { path = "../../", features = [
  "cursor",
  "embed-resource",
  "list-view",
  "no-styling"
] }

[build-dependencies]
embed-resource = "1.3"
