[package]
name = "native-windows-gui"
version = "1.0.12"
edition = "2024"
description = "A rust library to develop native GUI applications on the desktop for Microsoft Windows. Native-windows-gui wraps the native win32 window controls in a rustic API"
documentation = "https://gabdube.github.io/native-windows-gui/native-windows-docs/index.html"
repository = "https://github.com/gabdube/native-windows-gui"
license = "MIT"
keywords = ["gui", "ui", "windows"]
build = "build.rs"

[package.metadata.docs.rs]
# This also sets the default target to `x86_64-pc-windows-msvc`
features = ["all"]
all-features = false
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
bitflags = "1.1.0"
derive-setters = { path = "./derive-setters" }
enum_discriminant = "1.0.1"
lazy_static = "1.4.0"
muldiv = { version = "0.2", optional = true }
newline-converter = { version = "0.2.0", optional = true }
plotters = { version = "0.3", default-features = false, features = [
  "all_elements",
  "all_series"
], optional = true }
plotters-backend = { version = "0.3", optional = true }
# Integration for raw-window-handle
raw-window-handle = { version = "0.3.3", optional = true }
taffy = { version = "0.9.2", optional = true }
winapi = { version = "0.3", features = [
  "combaseapi",
  "commctrl",
  "commdlg",
  "d2d1",
  "dwrite",
  "errhandlingapi",
  "libloaderapi",
  "objbase",
  "processthreadsapi",
  "shellapi",
  "shobjidl",
  "stringapiset",
  "sysinfoapi",
  "winbase",
  "wincodec",
  "winerror",
  "wingdi",
  "winnls",
  "winuser"
] }

[dev-dependencies]
native-windows-derive = { path = "../native-windows-derive/" }

[build-dependencies]
winapi-build = "0.1.1"

[features]
default = ["all"]
all = [
  "animation-timer",
  "clipboard",
  "color-dialog",
  "combobox",
  "cursor",
  "datetime-picker",
  "dynamic_layout",
  "embed-resource",
  "extern-canvas",
  "fancy-window",
  "file-dialog",
  "flexbox",
  "font-dialog",
  "frame",
  "image-decoder",
  "image-list",
  "labeled",
  "list-view",
  "listbox",
  "menu",
  "message-window",
  "notice",
  "number-select",
  "plotting",
  "progress-bar",
  "rich-textbox",
  "scroll-bar",
  "status-bar",
  "tabs",
  "textbox",
  "tooltip",
  "trackbar",
  "tray-notification",
  "tree-view",
  "tree-view-iterator",
  "winnls"
]
animation-timer = []
clipboard = []
color-dialog = []
combobox = []
cursor = []
datetime-picker = []
dynamic_layout = []
embed-resource = []
extern-canvas = []
fancy-window = []
file-dialog = []
flexbox = ["taffy"]
font-dialog = []
frame = []
high-dpi = ["muldiv"]
image-decoder = []
image-list = []
labeled = ["flexbox"]
list-view = []
listbox = []
menu = []
message-window = []
no-styling = []
notice = []
number-select = []
plotting = ["plotters", "plotters-backend"]
progress-bar = []
raw-win-handle = ["raw-window-handle"]
rich-textbox = ["newline-converter"]
scroll-bar = []
status-bar = []
tabs = []
textbox = ["newline-converter"]
tooltip = []
trackbar = []
tray-notification = []
tree-view = []
tree-view-iterator = []
winnls = []
